name: first-action
on: workflow_dispatch
jobs:
  first-job:
      runs-on: ubuntu-latest
      steps:
        - name: Print hello
          run: echo "Hello"
        - name: Run multiple commands
          run: |
            echo "First line"
            echo "Second line"
        - name: Print bye
          run: echo "Bye"
